# Generated by Django 3.2.7 on 2021-09-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='link',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
